// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Suave = require("./Suave.bs.js");

var stores = [{
    number: 2304
  }];

var partial_arg = Suave.ok(stores);

var partial_arg$1 = Suave.ok("posted stores");

function partial_arg_0(param) {
  return Suave.$great$eq$great(Suave.get, partial_arg, param);
}

var partial_arg_1 = {
  hd: (function (param) {
      return Suave.$great$eq$great(Suave.post, partial_arg$1, param);
    }),
  tl: /* [] */0
};

var partial_arg$2 = {
  hd: partial_arg_0,
  tl: partial_arg_1
};

function partial_arg$3(param) {
  return Suave.choose(partial_arg$2, param);
}

var partial_arg$4 = Suave.path("/stores");

var partial_arg$5 = Suave.ok("got items");

var partial_arg$6 = Suave.ok("posted items");

function partial_arg_0$1(param) {
  return Suave.$great$eq$great(Suave.get, partial_arg$5, param);
}

var partial_arg_1$1 = {
  hd: (function (param) {
      return Suave.$great$eq$great(Suave.post, partial_arg$6, param);
    }),
  tl: /* [] */0
};

var partial_arg$7 = {
  hd: partial_arg_0$1,
  tl: partial_arg_1$1
};

function partial_arg$8(param) {
  return Suave.choose(partial_arg$7, param);
}

var partial_arg$9 = Suave.path("/items");

function partial_arg_0$2(param) {
  return Suave.$great$eq$great(partial_arg$4, partial_arg$3, param);
}

var partial_arg_1$2 = {
  hd: (function (param) {
      return Suave.$great$eq$great(partial_arg$9, partial_arg$8, param);
    }),
  tl: {
    hd: Suave.notFound("Like Bono, we still haven't found what you're looking for"),
    tl: /* [] */0
  }
};

var partial_arg$10 = {
  hd: partial_arg_0$2,
  tl: partial_arg_1$2
};

function api(param) {
  return Suave.choose(partial_arg$10, param);
}

exports.stores = stores;
exports.api = api;
/* partial_arg Not a pure module */
